---
version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Etc/UTC"

  # Maintain pip packages for acars_router
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Etc/UTC"
