---
name: Lint

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  # =====================================================================
  # Primary Lint job
  # =====================================================================
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run flake pre-commit hooks
        run: nix develop -c pre-commit run --all-files
